services:
  app:
    container_name: laravel_app

    build:
      context: ./backend
      dockerfile: Dockerfile

    # Laravel project will live here
    working_dir: /workspace/backend

    # Synchronize backend local folder into container
    volumes:
      - ./:/workspace
      - vendor_data:/workspace/backend/vendor

    depends_on:
      - db

    command: sh -c "
      composer install &&
      chmod -R 777 storage bootstrap/cache &&
      php artisan key:generate --force || true &&
      php artisan migrate &&
      php-fpm
      "
    networks:
      - laravel

    restart: unless-stopped

  vite:
    container_name: laravel_vite

    build:
      context: ./backend
      dockerfile: Dockerfile

    working_dir: /workspace/backend

    volumes:
      - ./:/workspace
      - node_modules_data:/workspace/backend/node_modules

    # Publish container port 5173  for Vite dev server
    ports:
      - '5173:5173'

    command: sh -c "npm install && npm run dev -- --host"

    depends_on:
      - app

    networks:
      - laravel

  nginx:
    container_name: laravel_nginx

    image: nginx:alpine

    # Publish container port 80 to localhost:8000
    ports:
      - '8000:80'

    # Give nginx access to project files Prefer container
    volumes:
      - ./backend:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app

    networks:
      - laravel

    restart: unless-stopped

  db:
    container_name: laravel_db

    image: mysql:8.0

    # Load MySQL credentials from .env file
    env_file:
      - ./backend/.env

    # Use native password plugin for compatibility with Laravel's MySQL driver
    command: --default-authentication-plugin=mysql_native_password

    # Expose MySQL for DBeaver debugging
    ports:
      - '3306:3306'

    volumes:
      - dbdata:/var/lib/mysql

    networks:
      - laravel

    restart: unless-stopped

# Used for persistent MySQL data, managed by Docker
volumes:
  dbdata:
  vendor_data:
  node_modules_data:

# Internal Docker network for container communication
networks:
  laravel:
